### ISSUE TITLE
Stock Market Sidebar Script?

### ISSUE THREAD

**Issue by jacobkossman** [w35l3y/userscripts#18]
Hey is it possible for you to update/revamp the neopets stock market sidebar script? that thing was super helpful! thanks!

**Comment by w35l3y** [comment]
Related to #32

**Comment by jawsch** [comment]
This seems to be broken now :(

**Comment by w35l3y** [comment]
Commit bad421aa867bec97c812ce44ed08e48a7a5b73b8 fixes #18
