### ISSUE TITLE
Food club bet

### ISSUE THREAD

**Issue by Maura79** [w35l3y/userscripts#20]
Hi, can you please add the food club script?
Thank you so much.

**Comment by w35l3y** [comment]
I searched in my backup and there isn't any script about food club.
What script did you mean ?

**Comment by Maura79** [comment]
Is a script that copies bets from a neopage and places them automatically.
I was convinced it was one of your scripts :(

**Comment by w35l3y** [comment]
No, what neopage?

**Comment by Maura79** [comment]
I follow Hugo on ~myfoodclubbets (but the scripts worked on every similar page).
It was enough to open that page, confirm the popup and then the script placed every bet on Food Club in Neopets.

**Comment by w35l3y** [comment]
Very good. I didn't know that.
Well, I'll keep this ticket open as an idea of new script, but I can't give you any guarantee that I'll implement it.

**Comment by w35l3y** [comment]
I found these versions of the same script:
* https://github.com/NeoquestBro/Scripts/blob/master/132450.user.js
* https://github.com/Soren-Nordstrom/userscript/blob/master/monolith/53/132450.user.js
* https://github.com/donrok/gambler/blob/master/food-club-better.user.js

I haven't tested them but I think only the first one works.

**Comment by w35l3y** [comment]
Created [Neopets : Food Club](https://github.com/w35l3y/userscripts/raw/master/scripts/Neopets_Food_Club/main.user.js)
