### ISSUE TITLE
Neopets_Battledome_Fight! Broken

### ISSUE THREAD

**Issue by iBubbless** [w35l3y/userscripts#25]
Browser: Firefox 34.0.5
Greasemonkey: 2.3 and 1.5
Script: Neopets_Battledome_Fight!
Accessed url: http://www.neopets.com/dome/arena.phtml
Error Message: "Clicking #start:visible" 161251.user.js:390
Obs.: This script was working up too the Battledome fix, now it won't trigger when using greasemonkey v1.15 and will prompt for the # of fights during v2.3 but will not choose weapons or scroll down. Using the console it looks like the script ends after the above error message.

It's essentially not picking the weapon/skill at the moment.

**Comment by w35l3y** [comment]
Thanks for your detailed message.
