### ISSUE TITLE
Pyramids player doesn't work for me

### ISSUE THREAD

**Issue by vkau** [w35l3y/userscripts#27]
**Browser:** (missing)
**Greasemonkey:** (missing)
**Script:** Neopets : Pyramids (1.0.0)
**Url:** http://www.neopets.com/games/pyramids/
**Error Message:** (missing)
**Obs.:** it just sits there and does nothing...

**Comment by w35l3y** [comment]
Are you sure? Because it should execute once every 1-3 seconds

**Comment by vkau** [comment]
yes, i'm sure

i just removed it, and reinstalled it again, and it is still not doing anything in the pyramids game

**Comment by vkau** [comment]
I have premium and use adblock. Could that make a difference in the format of the page that would keep it from playing pyramids? Other stuff works... dice-a-roo, solitaire, etc.

Cliffhanger says "no solution found" or something like that, but I assumed that was because I'm missing some sort of answers file...

**Comment by vkau** [comment]
also, if i have the script running, and i am playing pyramids manually, then i get a premium space faerie event, i can't advance the page by clicking the cards; i have to go back in through the pyramids front page

**Comment by w35l3y** [comment]
Being premium user might interfere with the source code of the page, but not adblock.
It is very difficult to solve these kind of problems without any further tecnical details.
Please, consider readind the [guidelines for contributing](../blob/master/CONTRIBUTING.md#reporting-issues) to help with more details.

**Comment by vkau** [comment]
**Browser:** Firefox 36.0
**Greasemonkey:** 2.3
**Script:** Neopets : Pyramids 1.0.0
**Accessed url:** 
www.neopets.com/games/pyramids/index.phtml
http://www.neopets.com/games/pyramids/pyramids.phtml
**Error Message:** none
**Obs.:** cards do not appear to be selected, and game does not advance; the script seems to have no effect at all

**Comment by w35l3y** [comment]
Was it fixed ? It was missing some metadata.

**Comment by vkau** [comment]
It wasn't fixed. I don't know what you mean by missing metadata. Thank you for your patience, since I don't know very much. I had to type in the information that your guidelines requested. Here is some more:


Operating system
Windows 7
IP address
66.172.XXX.XXX
Javascript enabled
Yes
Cookies enabled
Yes
Flash version
16.0.0
Java version
1.8.0_31
Websockets supported
Yes
Browser size
1904 x 985
Screen size
1920 x 1080
Color depth
24 bit
Your full user agent string is:
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:36.0) Gecko/20100101 Firefox/36.0

**Comment by w35l3y** [comment]
Press Ctrl+Shift+J (Error Console) and check if there is any error message related to the pyramids page or the script.
If you have any doubt, clean it and refresh the page.

Save the source code of the page and send to w35l3y@brasnet.org
Screenshots of the page and error console are welcome too.

**Comment by vkau** [comment]
sorry this took so long. neopets is super laggy. here are screen shots. when i just started the pyramids game, there was nothing in the console. after i clicked the two cards, i had this in the console. i will email you the page source.

![console_screenie](https://cloud.githubusercontent.com/assets/10979591/6190452/ab504694-b367-11e4-959c-01961b5af54b.jpg)
![pyramids_screenie](https://cloud.githubusercontent.com/assets/10979591/6190451/ab4f53c4-b367-11e4-8d7b-ffe2459ce76b.jpg)

**Comment by w35l3y** [comment]
Yes, you should remove them for security reasons.
You could attach them to the email along with the source code.

**Comment by vkau** [comment]
I deleted them from the photos I think. Does that stuff help at all? I'm sorry that I don't even know the right way to give you the data/information that you need. Thanks for all your help and patience (and for writing these scripts in the first place!).

**Comment by w35l3y** [comment]
Source code was decisive. You may try again now.

**Comment by vkau** [comment]
It's fixed! Great job!
