### ISSUE TITLE
Shop Wizard Improved Search not working for premium user

### ISSUE THREAD

**Issue by vkau** [w35l3y/userscripts#29]
This one never worked for me, but after you fixed the Pyramids one so quickly, I am optimistic. I emailed you the source code. Here is the other data:

Operating system
Windows 7
IP address
66.172.XXX.XXX
Javascript enabled
Yes
Cookies enabled
Yes
Flash version
16.0.0
Java version
1.8.0_31
Websockets supported
Yes
Browser size
1904 x 985
Screen size
1920 x 1080
Color depth
24 bit
Your full user agent string is:
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:36.0) Gecko/20100101 Firefox/36.0

**Comment by w35l3y** [comment]
It is related with e240e2b7957d2a10e65dfdec57e0168d68134d7a#commitcomment-9740060

**Comment by w35l3y** [comment]
Related to #32
