### ISSUE TITLE
Option for Faster Pyramids

### ISSUE THREAD

**Issue by vkau** [w35l3y/userscripts#30]
It would be nice to have an option to play pyramids faster. When I play manually, I play a lot faster than the default setting in this script. Thanks!

**Comment by w35l3y** [comment]
I currently am working on a different script, but you may try to change your own installed version.
Just edit [line 44](../blob/master/scripts/Neopets_Pyramids/main.user.js#L44) to any lower values you want.
1232 is the constant part and 1567 is the variable part.
I mean, currently it varies from 1232 to 2799 (1232 + 1567)

**Comment by vkau** [comment]
thanks!
