### ISSUE TITLE
Quick price Checker

### ISSUE THREAD

**Issue by Kurowaru** [w35l3y/userscripts#34]
Please update it to work with the new neopets code or whatever since it stopped working.
AKA the reminder you asked me to fill in (I just followed the link in the mail btw, so not sure this is the correct place to submit it XD)
TYSM! :D

**Comment by w35l3y** [comment]
Yes, this is the right place to report any error from this repository.
I just fixed the relative paths of [Neopets : Quick Price Checker](../tree/master/scripts/Neopets_Quick_Price_Checker)

You should give a try to [Neopets : Price Checker](../tree/master/scripts/Neopets_Price_Checker) again.
I fixed some minor bugs that might have something to do with your last report by e-mail.
