### ISSUE TITLE
Most scripts not working on Neopets for me

### ISSUE THREAD

**Issue by stoplightgodess** [w35l3y/userscripts#35]
Hi w35l3y, 
I stalked you over from userscripts but have been having an issue with pretty much all your userscripts on neo. Whenever I open a page that has one of your scripts active, there is a translucent dark layer over the entire page and I cannot open any links on the page. Clearing my cache/full history or restarting Firefox or the computer and reinstalling hasn't worked. I am particularly concerned for the Battledome, SHop Wizard and Dailies helpers as those have been invaluable in the past. The avatar beta is working, which was a very pleasant surprise, but I am at a complete loss for what to do. This is what appears in the Ctrl+Shift+J window:

"DEPRECATED: The widget module is deprecated.  Please consider using the sdk/ui module instead.
Traceback (most recent call last):
  File "resource://gre/modules/Promise-backend.js", line 867, in Handler.prototype.process
    nextValue = this.onResolve.call(undefined, nextValue);
  File "resource://gre/modules/commonjs/sdk/addon/runner.js", line 86, in startup/</<
    run(options);
  File "resource://gre/modules/commonjs/sdk/addon/runner.js", line 145, in run
    let program = main(options.loader, options.main);
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 740, in main
    return loader.load(loader, module).exports;
  File "resource://gre/modules/commonjs/sdk/loader/cuddlefish.js", line 79, in CuddlefishLoader/options<.load
    result = load(loader, module);
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 332, in load
    evaluate(sandbox, module.uri);
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 280, in evaluate
    : loadSubScript(uri, sandbox, encoding);
  File "resource://jid1-n85lxpv1nawvtq-at-jetpack/freememory/lib/main.js", line 19, in null
    const widget = require("widget");
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 625, in require
    freeze(load(loader, module));
  File "resource://gre/modules/commonjs/sdk/loader/cuddlefish.js", line 79, in CuddlefishLoader/options<.load
    result = load(loader, module);
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 332, in load
    evaluate(sandbox, module.uri);
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 280, in evaluate
    : loadSubScript(uri, sandbox, encoding);
  File "resource://jid1-n85lxpv1nawvtq-at-jetpack/freememory/lib/widget.js", line 6, in null
    const widgets = require("sdk/widget");
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 625, in require
    freeze(load(loader, module));
  File "resource://gre/modules/commonjs/sdk/loader/cuddlefish.js", line 79, in CuddlefishLoader/options<.load
    result = load(loader, module);
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 332, in load
    evaluate(sandbox, module.uri);
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 280, in evaluate
    : loadSubScript(uri, sandbox, encoding);
  File "resource://gre/modules/commonjs/sdk/widget.js", line 59, in null
    require("./util/deprecate").deprecateUsage(
  File "resource://gre/modules/commonjs/sdk/util/deprecate.js", line 18, in deprecateUsage
    let stack = get().slice(2);" deprecate.js:21
Object { stack: "", 5 more… } runner.js:164
Object { stack: "", 5 more… } Promise-backend.js:870
"OX: no zone map found" forbes_welcome.js:1:3060
"This browser is AJAX compatible" vbulletin-core.js:11:10737
"Firing System Init" vbulletin-core.js:11:26208
"Fire vB_XHTML_Ready" vbulletin-core.js:11:29535
"Fetch Cookie :: vbulletin_collapse (null)" vbulletin-core.js:11:17103
"Received message of type object from http://platform.twitter.com, expected a string" sdk.js:64:239
"Bubble Analytics" Array [ <1 empty slot> ] loaded.js:4:12260
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create frameworks-5e259e3a6935d5ff682e39b29c2718eccd1c93dca272dcc4c45faacef0d1a340.js:34:1559
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create frameworks-5e259e3a6935d5ff682e39b29c2718eccd1c93dca272dcc4c45faacef0d1a340.js:34:1559
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. jquery-1.7.1.min.js:3:0
invalid 'in' operand config 61379.user.js:484:0
This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.[Learn More] fbds.js
This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.[Learn More] tr
TypeError: invalid 'in' operand g 163374.user.js:324:3
TypeError: invalid 'in' operand g 163374.user.js:324:3

**Comment by w35l3y** [comment]
Did you mean :
[Battledome : Fight!](../blob/master/scripts/Neopets_Battledome_Fight!)
[Dailies To-Do](../blob/master/scripts/Neopets_Dailies_To-Do)
[Shop Wizard : Improved Search](../blob/master/scripts/Neopets_Shop_Wizard_Improved_Search)

How recently you installed them?

`TypeError: invalid 'in' operand g 163374.user.js:324:3`
This is the most important part in your error message.

Thanks for your help.

**Comment by mediterra2** [comment]
Battledome - Fight! seems to have just stopped working for me.  I think it
stopped working right after the battledome was down for a few days.

**Comment by stoplightgodess** [comment]
Hi. I uninstalled and reinstalled the scripts from here on GitHub last week. I had previously been using them and several others from the userscripts mirror site.

**Comment by mediterra2** [comment]
Is the battledome fight script working or is it just me?   For me, it
stopped working after the battledome was down for several days.

**Comment by mediterra2** [comment]
Is it possible to do a script that that would periodically (say every 5
mins) check if there are any TP offers or unread mails, and then, produce
an audible alarm.  That would be amazing if it could be done.  Basically,
it would just require refreshing the page and checking if there is an email
or offer icon above "my account" in the upper left.

I don't know how many times I've missed offers for I/J quests or for the
Kadoaterie.

**Comment by w35l3y** [comment]
I know the problem is in [Includes : WinConfig](https://github.com/w35l3y/userscripts/blob/master/includes/Includes_WinConfig/163374.user.js), but I will be busy for the next months or so.

Anyone is welcome to fix it and pull a request.

In the mean time, you may consider changing the script where it says "../../includes/Includes_WinConfig/163374.user.js" to "https://github.com/w35l3y/userscripts/raw/ef6e31321e413522d3133d884941aaedcaf63169/includes/Includes_WinConfig/163374.user.js"
The same could be done to all other scripts with the same problem.

**Comment by idoteko** [comment]
I also had a translucent grey screen over Neopets with scripts not working.

Changing the script didn't work, however, a solution I found that did work was downgrading FF and GM to a version of around when these scripts were created (which is probably not advised due to all the security risk that opens up).

However,

They are working flawlessly now.

**Comment by stoplightgodess** [comment]
Im not sure which version that would be but would be massively appreciative if you could share the links. Also, odd thing, tried out the same scripts on my Mac at home and most of them (sans the Batledome script which simply shows the number of times to battle and nothing else) are working there. Will try the fix you suggested w35l3y on that and let you know if that works this evening.

**Comment by andersonthiago** [comment]
Idoteka, what versions did you install??? Don't worked for me...

**Comment by w35l3y** [comment]
I have updated all scripts to update their dependencies.
They should work now.

Thank you all
