### ISSUE TITLE
Neopets : Faerie Crossword

### ISSUE THREAD

**Issue by Sassenach** [w35l3y/userscripts#36]
The Faerie Crossword script stopped working for me a few days ago.  I updated a few scripts from here and it might have been one of them and now the crossword just sits there without doing anything.  Any suggestions?
PS.  I use a whole lot of your neopets scripts.  They are most appreciated.

In case it's relevant I'm using Firefox 33.0.3 and a Macbook Pro running OS 10.9.4

**Comment by jacobkossman** [comment]
I have a working version [here](https://github.com/jacobkossman/userscripts-1/blob/master/scripts/Neopets_Faerie_Crossword/76450.user.js) @Sassenach. Just install over the previous script.

@w35l3y, I submitted a pull request.

**Comment by Sassenach** [comment]
Installed and working. #myhero

**Comment by w35l3y** [comment]
Commit a70bac7ebce47dae14cf28af982d23193a76961b should close this issue.
