### ISSUE TITLE
Avatars Flash Games issue.

### ISSUE THREAD

**Issue by Vorarephilia** [w35l3y/userscripts#39]
Hello, I'm trying to get the Neopets : Avatars Flash Games script to work on Firefox with Greasemonkey, but I can't. I have tried literally anything and I just don't get it anymore. My friend, who showed me this script did get it to work a couple of months ago, and we have the same version of Firefox and Greasemonkey. I know which games to use it on, but the little monkey that is supposed to show isn't. Am I doing something wrong?

**Comment by w35l3y** [comment]
Thanks for letting me know!
This should be fixed by now. Just try to reinstall it.
