### ISSUE TITLE
Includes_Neopets_Battledome/main.user.js?

### ISSUE THREAD

**Issue by jkingaround** [w35l3y/userscripts#42]
Can you possibly make a readme for the required params for the fight function? Trying to make a script to select my weapons and fight but can't figure it out :stuck_out_tongue:

thanks!

**Comment by w35l3y** [comment]
Did you mean [this](https://github.com/w35l3y/userscripts/blob/master/scripts/Neopets_Battledome_Fight!/append-README.md)?

**Comment by jacobkossman** [comment]
No I mean the actual include, since that script no longer functions :)

**Comment by jkingaround** [comment]
No I mean the actual include, since that script no longer functions :)

**Comment by w35l3y** [comment]
Have you tried to reinstall it recently?
It works fine to me.

Please, consider reading the guidelines for contributing before creating an issue about any non-working script.

Ok, I will add a readme for that include, but this one isn't used in any public script. Thanks

**Comment by w35l3y** [comment]
Added [README](https://github.com/w35l3y/userscripts/blob/master/includes/Includes_Neopets_Battledome/append-README.md) ( 41c5bae )

**Comment by mediterra2** [comment]
Thanks for getting it working again.  We missed it.  It works great on my and all but one of my friends' computers.  The one friend has to manually "help it along" sometimes, but she's still happy with it.

**Comment by w35l3y** [comment]
That is probably because she has a very slow internet connection.
The script checks once in a while for the buttons to click. If they aren't found in a reasonable time, it refreshes the page automatically.
Ask her to increase the wait time between steps (default 515 miliseconds) in the Settings (default Ctrl+Shift+Alt+S)
