### ISSUE TITLE
Food Club Include - Doesn't return anything anymore?

### ISSUE THREAD

**Issue by jkingaround** [w35l3y/userscripts#43]
**Browser:** Firefox<br />
**Greasemonkey:** 3.7<br />
**Script:** Includes_Neopets_FoodClub<br />
**Accessed url:** https://github.com/w35l3y/userscripts/tree/master/includes/Includes_Neopets_FoodClub<br />
**Installation url:** URL<br />
**Error Message:** `Object { error: false, errmsg: "", body: HTMLDocument, 1 more… }`<br />
**Obs.:** Made my own foodclub better using your include and a couple of additional functions i added to actually bet and it stopped working recently. I'm not sure why it stopped working but i can't seem to get it to return the proper values.<br />

**Comment by w35l3y** [comment]
In your case that is a developer, more details like which function and parameters that you used are very welcome.
An example of code, etc.

**Comment by jkingaround** [comment]
I ended up figuring out it was in the "response" in the Object (rather than on it's own?)

Something changed somewhere and i have to pass a function directly to use it instead of calling "onsuccess" or "callback". I'll get it working again and then post it here.

**Comment by jkingaround** [comment]
here is the userscript i made based on your include and my added functionality to allow betting from reddit urls and to place the bets. i'm sure you can make it better :stuck_out_tongue: 

http://pastebin.com/9p1pjWWR

**Comment by w35l3y** [comment]
Here's what I did based on yours: http://pastebin.com/fhRPeMss
