### ISSUE TITLE
Inventory - Give to NF

### ISSUE THREAD

**Issue by jkingaround** [w35l3y/userscripts#44]
**Browser:** Firefox<br />
**Greasemonkey:** 3.7<br />
**Script:** Includes : Inventory<br />
**Error Message:** `Object { result: "Who do you wish to give this Gorund…" }`<br />
**Obs.:** Giving to neofriend doesn't work? Just asks who to give to. I added the "or_name" into the data object but it didn't work?<br />

`invent.list({
    callback : function(o){
        invent.info({
            obj_id : o.response.items[0].obj_id,
            callback : function(obj){
                invent.use({
                    data : {
                        obj_id : obj.response.item.obj_id,
                        or_name : "username_here",
                        action : "give"
                    },
                    callback : function(o){
                        console.log(o.response);
                    }
                });
            }
        });
    }
});
`

**Comment by w35l3y** [comment]
The default process of giving items is 2-step. You may try to use the action "Give to USERNAME" instead of just "give".
