### ISSUE TITLE
Premium Events

### ISSUE THREAD

**Issue by jkingaround** [w35l3y/userscripts#45]
**Browser:** Firefox<br />
**Greasemonkey:** 3.7<br />
**Script:** Includes : Neopets [BETA]<br />
**Obs.:** Doesn't grab premium events as an event. Using it to create a basic event logger<br />

here's the HTML for a premium event
```
<div id="shh_prem_bg" class="en">
	<div class="shh_prem_frame">
		<div id="shh_prem_faerie">
		</div>
		<div id="shh_prem_img" style="background-image: url('http://images.neopets.com/common/bag_of_np.gif');"></div>
			<div class="desc_outer"> 
				<div class="desc_middle">
                                    <div class="desc_inner">
					    Congratulations, username, you just found <b>1,322</b> Neopoints!
                                        </div>
				</div>
			</div>

		</div>
	</div>
```

**Comment by w35l3y** [comment]
Cool!
Do you think you have expertise to suggest a pull request containing this fix?

**Comment by jkingaround** [comment]
I could try. Which one is the most "recent" that you are using? Since the "random events" one exists as well.

**Comment by w35l3y** [comment]
I didn't understand. What are the options?
The fix is to include premium events along with the others events.

**Comment by jkingaround** [comment]
There's [this](https://github.com/w35l3y/userscripts/tree/master/includes/Includes_Neopets_Random_Events) and [this](https://github.com/w35l3y/userscripts/tree/master/includes/Includes_Neopets_%5BBETA%5D)

**Comment by w35l3y** [comment]
Oh, I see! Well, I didn't even remember "Includes : Neopets : Random Events" :D

You would help by modifying any of them. Any help is appreciated.
I will try to work on it tomorrow.

Thanks

**Comment by w35l3y** [comment]
Did it work? Have you tested it?

**Comment by jkingaround** [comment]
Yes. It works! I was literally about to work on it haha
