### ISSUE TITLE
Food Club

### ISSUE THREAD

**Issue by xChoppie** [w35l3y/userscripts#47]
The food club script works well but it only places 9 bets.
I used http://www.neopets.com/~boochi_target.

Would appreciate if you could fix this. 
Thanks for the script!

**Comment by w35l3y** [comment]
Are you sure?
Because it goes from 0 to 9, I mean, 0 is the first bet.
0,1,2,3,4,5,6,7,8,9 (10 bets)

I will update the script to go from 1 to 10, but I don't think it is skipping one bet.
