### ISSUE TITLE
[enhancement] Battledome Fight Cancel Button / Shortcut

### ISSUE THREAD

**Issue by jkingaround** [w35l3y/userscripts#48]
**Browser:** Chrome (Latest)<br />
**Greasemonkey:** 3.8<br />
**Script:** Battledome: Fight!<br />

Was wondering if you could implement some sort of cancellation? I accidentally added a 0 when i went to put in the number and it's fighting 250 times XD A keyboard shortcut or button of some sort would be nice 👍

**Comment by w35l3y** [comment]
Does it work in Chrome?!
