### ISSUE TITLE
Retrieve Food Club Bets

### ISSUE THREAD

**Issue by xChoppie** [w35l3y/userscripts#50]
Hi w35l3y,
Would it be possible to enhance the food club script such that it is able to retrieve bets from reddit? 

E.g., 
- Food Club Bets Page: https://www.reddit.com/r/neopets/comments/4oi2eo/food_club_bets_june_17_2016/
- Reddit User's Overview Page: https://www.reddit.com/user/twoforjoy

Thank you for the script! :)

**Comment by w35l3y** [comment]
Try reinstalling the script and let me know. Thanks
