### ISSUE TITLE
No letter for captcha image in games script?

### ISSUE THREAD

**Issue by Cryptker** [w35l3y/userscripts#52]
**Browser:** (NAME VERSION)<br />
**Greasemonkey:** (VERSION)<br />
**Script:** (NAME VERSION)<br />
**Accessed url:** (URL THAT YOU WERE WHEN THE ERROR OCCURRED)<br />
**Installation url:** (URL THAT YOU USED TO INSTALL THE SCRIPT) [ Only if the script doesn't work since installation ]<br />
**Error Message:** (MESSAGE) [ Add filename and line number too. A printscreen is an option. Usually found in the Error Console : Ctrl+Shift+J ]<br />
**Obs.:** (OTHERS OBSERVATIONS THAT YOU CONSIDER RELEVANT)<br />
**Expected behavior:** (EXPECTED)<br />
**Actual behavior:** (ACTUAL)<br />
**Steps to reproduce:**<br />
 1. -
 2. -

**Example of code**: [Only if you know what it means]
<pre>CODE HERE</pre>

**Comment by w35l3y** [comment]
The ISSUE TEMPLATE was supposed to be filled with informations that make the fix easier.

I used to use showmycode.com to decompile SWF files, required to encrypt the URL needed to send score.
ShowMyCode was closed, so I cannot use it anymore.

I didn't find any other online API that does what showmycode used to do.
**If you or anyone else know other online API that does the same, please let me know.**

So, currently **the only workaround is to check "Try cached encryption"**.
This way, the captcha isn't required whether you have encryption cached.

**Comment by Cryptker** [comment]
Tried that it doesn`t work either on Firefox or chrome neither are working
for me,I have the latest browsers installed and have tried it on waterfox
also and with or without the captcha and it`s not working. 
 
 
 
 
-------Original Message-------
 
From: w35l3y
Date: 10/31/17 09:29:45
To: w35l3y/userscripts
Cc: Cryptker;  Author
Subject: Re: [w35l3y/userscripts] No letter for captcha image in games
script? (#52)
 
The ISSUE TEMPLATE was supposed to be filled with informations that make the
fix easier.
I used to use showmycode.com to decompile SWF files, required to encrypt the
URL needed to send score.
ShowMyCode was closed, so I cannot use it anymore.
I didn't find any other online API that does what showmycode used to do.
If you or anyone else know other online API that does the same, please let
me know.
So, currently the only workaround is to check "Try cached encryption".
This way, the captcha isn't required whether you have encryption cached.

**Comment by w35l3y** [comment]
Then you haven't the encryption cached. It won't work for you.

It is cached by default when you use it with the captcha at least once for each encryption file (it depends from game to game).
Some games share the same encryption file.
