### ISSUE TITLE
Faerie Crossword no longer works after update

### ISSUE THREAD

**Issue by birdgofly** [w35l3y/userscripts#53]
**Browser:** Firefox 56.0.2<br />
**Plugin:** Greasemonkey 3.17<br />
**Script:** Faerie Crossword 3.0.6<br />

Faerie Crossword Script does not work for me since update to 3.0.6; it will start the puzzle but will not fill it out - it will not even pull the first answer. I went back to 3.0.4 and it still works great! Thought I'd let you know. Thank you for your great scripts!

**Comment by w35l3y** [comment]
Uninstall and reinstall it.
This will remove all stored legacy data that is preventing the script from working.

Thanks for letting me know.

**Comment by birdgofly** [comment]
Oops, sorry, I didn't know that could happen! I ended up having to uninstall and close Firefox, reopen Firefox and reinstall, and then close Firefox again, and when I reopened Firefox, it worked! Thank you again!
