### ISSUE TITLE
null at http://gm.wesley.eti.br/icon.php?desc=127882

### ISSUE THREAD

**Issue by Rewny** [w35l3y/userscripts#64]
**Browser:** Firefox|<br />
**Plugin:** Greasemonkey|<br />
**Script:** Neopets : Avatars Flash Games [BETA]<br />

When attempting to install I am receiving the following error message:
**Error Message:** null at http://gm.wesley.eti.br/icon.php?desc=127882<br />

**Comment by w35l3y** [comment]
This should be fixed by now. Thanks for letting me know.
It was caused due to recent changes on DNS server.
