### ISSUE TITLE
Faerie Crosswords Redirect Source

### ISSUE THREAD

**Issue by silentium343** [w35l3y/userscripts#66]
**Browser:** Chrome<br />
**Plugin:** Tampermonkey<br />
**Script:** Faerie Crossword<br />
**Accessed url:** http://www.neopets.com/games/crossword/crossword.phtml<br />

**Error Message:** Request was redirected to a not whitelisted URL<br />
**Obs.:** Deleting all references of the .br domain portion of the cluesandanswers.blogspot.com.br fixed the issue entirely i.e cluesandanswers.blogspot.com<br />
**Expected behavior:** Play faerie crossword<br />
**Actual behavior:** No action. Console error log<br />
**Steps to reproduce:**<br />
 1. - Install Script
 2. - Visit crossword page and view console

**Comment by w35l3y** [comment]
Thanks for letting me know.
This should be fixed by now.
