### ISSUE TITLE
Faerie Crossword 

### ISSUE THREAD

**Issue by silentium343** [w35l3y/userscripts#67]
**Browser:** Chrome X.Y.Z<br />
**Plugin:** Tampermonkey X.Y.Z<br />
**Script:** Faerie Crossword<br />
**Accessed url:** http://www.neopets.com/games/crossword/crossword.phtml<br />
**Error Message:** Refused to connect to "http://www.jellyneo.net/?go=fcrossword": URL is not a part of the @connect list<br />
**Obs.:** Could not fix it this time.<br />

**Steps to reproduce:**<br />
 1. - Install Script
 2. - Visit http://www.neopets.com/games/crossword/crossword.phtml

**Comment by silentium343** [comment]
![image](https://user-images.githubusercontent.com/37456473/46052725-3bf96f00-c105-11e8-9397-0516a7461ef5.png)



After reinstalling.

**Comment by w35l3y** [comment]
Have you uninstalled the script first?
"Uninstall + Install" is different of "Reinstall"

**Comment by silentium343** [comment]
Uninstalled + Installed. Issue is gone. I am almost 100% sure I did that previously, but I cannot say for certain. Works fine now. If it happens again I'll let you know.
