### ISSUE TITLE
Captcha Issue

### ISSUE THREAD

**Issue by sherbertside** [w35l3y/userscripts#72]
**Browser:** Waterfox
**Plugin:** Tampermonkey
**Script:** Neopets : Avatars Flash Games [BETA]
**Accessed url:** http://www.neopets.com/games/game.phtml?game_id=412
**Actual behavior:** I know there have been previous mentions of the captcha site no longer working, but is there a way to get the "try cached encryption' to work? It seems I cant use either .<br />
![Screen Shot 2021-09-29 at 8 26 48 PM](https://user-images.githubusercontent.com/91641893/135366735-9f4cea05-34d5-4d74-80fc-9483b226762a.png)

**Comment by w35l3y** [comment]
Duplicate of #59
